spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formate-sql: true
    database: postgresql


application:
  security:
    jwt:
      secret-key: iF0LkfwR/pkA36x7Y7Q/jF6+PDURj5rpvvDGXnW+c4CG4hE=
      expiration: 828144